IMID=OVIMPOJ-Holo
SOURCES=OVCIN OVCandidateList OVFileHandler OVStringToolKit \
	OVIMPOJ-Holo POJ-Holo

DATA=poj-holo.cin

include ../../Mk/ov.os.mk
include ../../Mk/ov.im.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk
