# Makefile.Linux by vgod for OV 0.7

LOADER_DIR=Loaders/SCIM/
HDRDIR=Headers
HEADERS=OpenVanilla.h OVLibrary.h OVUtility.h
TARGET_DIR=/usr/local/include/OpenVanilla

all: framework loader

framework:
	mkdir -p $(TARGET_DIR)
	for file in $(HEADERS) ; do cp $(HDRDIR)/$$file $(TARGET_DIR)/; done;

loader:
	make -C $(LOADER_DIR)
