OBJS=AddPlist.o VXUtility.o
GOALS=AddPlist

all: $(GOALS)

$(GOALS): $(OBJS)
	$(CPP) -framework Cocoa -o $@ $(OBJS)

clean:
	$(RM) $(GOALS)

include ../../Mk/ov.osx.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk


