#!/bin/sh
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-array30.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-cj.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-cj-j.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-qcj.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-tcj.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-scj7.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-simplex.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-simplex.cin maxKeySequenceLength integer 2
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-dayi3.cin shiftSelectionKey integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-pinyinbig5.cin maxKeySequenceLength integer 10
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-zhcn_jtcj.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-zhcn_pinyin.cin maxKeySequenceLength integer 10
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-bopomofo.cin maxKeySequenceLength integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-bopomofo.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-liu57.cin maxKeySequenceLength integer 4 
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-liu57.cin autoCompose integer 1 
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-liu57.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-daibuun.cin maxKeySequenceLength integer 12
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-pictograph.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-pictograph.cin maxKeySequenceLength integer 4
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-pictograph.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-corner.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-corner.cin maxKeySequenceLength integer 4
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-corner.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-ehq.cin maxKeySequenceLength integer 6
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-iroha.cin maxKeySequenceLength integer 5
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-iroha.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-kk.cin maxKeySequenceLength integer 2
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-kk.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-klingon.cin maxKeySequenceLength integer 1 
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-klingon.cin autoCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist IM-OVIMXcin-klingon.cin hitMaxAndCompose integer 1
./AddPlist /Library/OpenVanilla/0.6.3/OVLoader.plist OVLoader currentIM string OVIMPhonetic
chmod 666 /Library/OpenVanilla/0.6.3/OVLoader.plist
