/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you want native library runtime debugging code enabled */
/* #undef ENABLE_DEBUG */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the `memchr' function. */
#define HAVE_MEMCHR 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `mkdir' function. */
#define HAVE_MKDIR 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* The binary version of libchewing. */
#define LIBCHEWING_BINARY_VERSION "1.0.0"

/* The release version of libchewing. */
#define LIBCHEWING_VERSION "0.3.0"

/* Name of package */
#define PACKAGE "libchewing"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "chewing-devel@googlegroups.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libchewing"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libchewing 0.3.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libchewing"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.3.0"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Runtime is under POSIX environment */
#define UNDER_POSIX 1

/* Runtime is under Win32 environment */
/* #undef UNDER_WIN32 */

/* Version number of package */
#define VERSION "0.3.0"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */
