// This file was generated by Dashcode from Apple Computer, Inc.
// You may edit this file to customize your Dashboard widget.

var preholder = "";

function load()
{
	setupParts();
	
	if (OVFilter) {
		var line = OVFilter.genList();
	}  
	if(line) {
	    line = "<select id=\"myfilter\" style=\"width:180px;\"" + line + "</select>";		
	    document.getElementById("filters").innerHTML= line;
	    document.getElementById("myfilter").selectedIndex = 0;	
	} else {
	    document.getElementById("filters").innerHTML= "Unable to load Modules";
	}
	if (window.getLocalizedString) {
		document.getElementById("input").value = getLocalizedString("Please input text here...");
	} else {
		document.getElementById("input").value = "Please input text here...";
	}
	preholder = document.getElementById("input").value;
}

function remove()
{
	// your widget has just been removed from the layer
	// remove any preferences as needed
	// widget.setPreferenceForKey(null, createInstancePreferenceKey("your-key"));
}

function hide()
{
	// your widget has just been hidden stop any timers to
	// prevent cpu usage
}

function show()
{
	// your widget has just been shown.  restart any timers
	// and adjust your interface as needed
}

function showBack(event)
{
	// your widget needs to show the back

	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToBack");

	front.style.display="none";
	back.style.display="block";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

function showFront(event)
{
	// your widget needs to show the front

	var front = document.getElementById("front");
	var back = document.getElementById("back");

	if (window.widget)
		widget.prepareForTransition("ToFront");

	front.style.display="block";
	back.style.display="none";
	
	if (window.widget)
		setTimeout('widget.performTransition();', 0);
}

if (window.widget)
{
	widget.onremove = remove;
	widget.onhide = hide;
	widget.onshow = show;
}


function convert(event) 
{
	document.getElementById("output").value = "Converting";
    var myinput = document.getElementById("input").value;
    var myfilter = document.getElementById("myfilter").value;
	if (OVFilter) {
		// var myoutput = OVFilter.myConvert_(myinput, myfilter);
		var myoutput = OVFilter.myConvert(myinput, myfilter);		
	}
	if(myoutput) document.getElementById("output").value = myoutput;
}


function clearDefaultText(event) 
{
	if(document.getElementById("input").value == preholder) {
		document.getElementById("input").value = "";
	}
}


function resetDefaultText(event) 
{
	if(document.getElementById("input").value == "") {
		document.getElementById("input").value = preholder;
	}
}
