IMID=OVOFReverseLookup

SOURCES=OVCIN OVCandidateList OVFileHandler OVOFReverseLookup\
     	OVStringToolKit XcinCinList

DATA=cj-lookup.cin phonetic-lookup.cin poj-lookup.cin array-lookup.cin

include ../../Mk/ov.os.mk
include ../../Mk/ov.im.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk