// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained by Dashcode.

/*
 getLocalizedString() pulls a string out an array named localizedStrings.  Each language project directory in this widget contains a file named "localizedStrings.js", which, in turn, contains an array called localizedStrings.  This method queries the array of the file of whichever language has highest precedence, according to the International pane of System Preferences.
 */
function getLocalizedString(string)
{
	try { string = localizedStrings[string] || string; } catch (e) {}
	return string;
}

/*
 createInstancePreferenceKey() returns a unique preference key that is based on a instance of an opened widget. The returned value can then be used in widget.setPreferenceForKey() and widget.preferenceForKey() so that the value that is set or retrieved is only for a particular opened widget.
 */
function createInstancePreferenceKey(key)
{
	return widget.identifier + "-" + key;
}
