# An IM makefile defines OBJS and GOALS, and the direct rule
# to build GOALS from your OBJS. Other rules are deal in ov.*.mk
IMID=OVIMUIM
# OBJS=OVIMUIM.o
# GOALS=OVIMUIM.dylib

OVIMUIM.dylib : OVIMUIM.mm
	gcc -framework Cocoa -framework UIM -bundle -o OVIMUIM.dylib OVIMUIM.mm

# $(GOALS): $(OBJS)
#	$(CPP) -framework Cocoa -framework UIM -bundle -o $@ $<

# include ../../Mk/ov.im.mk
# include ../../Mk/ov.vars.mk
# include ../../Mk/ov.general.mk
# include ../../Mk/ov.osx.mk


