IMID=OVIMezbasic
OBJS=OVIMezbasic.o ineval.o
GOALS=OVIMezbasic.dylib

$(GOALS): $(OBJS)
	$(CPP) -bundle -o $@ $(OBJS)

include ../../Mk/ov.im.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk
include ../../Mk/ov.osx.mk


