IMID=OVIMChewing


SOURCES=OVIMChewingStatic Chewingpp \
	char chewingio chewingutil choice dict hanyupinying \
	hash key2pho tree userphrase zuin

DATA=chewingdata/ch_index.dat chewingdata/dict.dat chewingdata/fonetree.dat chewingdata/ph_index.dat chewingdata/pinyin.tab chewingdata/us_freq.dat

include ../../Mk/ov.os.mk
include ../../Mk/ov.im.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk
INC+=-I./libchewing
VPATH+= ./libchewing/

