#include "VTCandidateController.h"
#include "VTHorizontalCandidateController.h"
#include "VTHorizontalCandidateView.h"
#include "VTVerticalCandidateController.h"
#include "VTVerticalCandidateTableView.h"
#include "VTVerticalKeyLabelStripView.h"
