IMID=OVIMPhoneticSQLite
SOURCES=OVIMPhoneticSQLite OVPhoneticLib

LDFLAGS=-lsqlite3
DATA=bpmf.db
CINS=bpmf.cin punctuation.cin

all: OVIMPhoneticSQLite.dylib bpmf.db

include ../../Mk/ov.os.mk
include ../../Mk/ov.im.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk

bpmf.db: bpmf-schema.txt ${CINS} bpmf-sqlconvert.pl
	rm -f bpmf.db
	sqlite3 bpmf.db < bpmf-schema.txt
	cat ${CINS} | perl bpmf-sqlconvert.pl | sqlite3 bpmf.db




