# An IM makefile defines IMID, SOURCES, and DATA , and the direct rule
# to build GOALS from your OBJS. Other rules are deal in ov.*.mk
IMID=OVIMArray
SOURCES=OVIMArray OVCIN OVStringToolKit OVFileHandler OVCandidateList
DATA=ArrayShortCode.cin array30.cin ArraySpecial.cin

include ../../Mk/ov.os.mk
include ../../Mk/ov.im.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk
