OBJS=AddPlist.o OVStringToolKit.o OVFileHandler.o OVCandidateList.o
GOALS=AddPlist

all: $(GOALS)

$(GOALS): $(OBJS)
	$(CPP) -framework Cocoa -o $@ $(OBJS)

clean:
	$(RM) $(GOALS)

include ../../Mk/ov.osx.mk
include ../../Mk/ov.vars.mk
include ../../Mk/ov.general.mk
INC=-I../../Headers/OSX -I../../Headers
